sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

before_script:
  - docker-compose pull

script:
  - docker-compose run --rm -e JEKYLL_ENV=production jekyll jekyll build

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
