defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
